// This file is @generated by prost-build.
/// Register a User.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterUserRequest {
    /// UUIDv4 identifier for the user.
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// The user's wallet public address.
    #[prost(string, tag = "2")]
    pub wallet_address: ::prost::alloc::string::String,
}
/// Register a node.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterNodeRequest {
    /// The type of this node.
    #[prost(enumeration = "NodeType", tag = "1")]
    pub node_type: i32,
    /// The owner of the node.
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
/// Response to a node registration request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterNodeResponse {
    /// The node's ID.
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
}
/// Request a prover task.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofTaskRequest {
    /// This node's ID.
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// The type of this node.
    #[prost(enumeration = "NodeType", tag = "2")]
    pub node_type: i32,
}
/// A Prover task.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofTaskResponse {
    /// Program id. (Assuming client-side default programs)
    #[prost(string, tag = "1")]
    pub program_id: ::prost::alloc::string::String,
    /// Public inputs to the program.
    #[prost(bytes = "vec", tag = "2")]
    pub public_inputs: ::prost::alloc::vec::Vec<u8>,
}
/// Submit the result of a prover task.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitProofRequest {
    /// The prover node's ID.
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// The type of this node.
    #[prost(enumeration = "NodeType", tag = "2")]
    pub node_type: i32,
    /// Hash of the proof.
    #[prost(string, tag = "3")]
    pub proof_hash: ::prost::alloc::string::String,
    /// Telemetry data about the node
    #[prost(message, optional, tag = "4")]
    pub node_telemetry: ::core::option::Option<NodeTelemetry>,
    /// ZK proof of the proof activity
    #[prost(bytes = "vec", tag = "5")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
}
/// Performance stats of a node.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeTelemetry {
    /// Flops per second
    #[prost(int32, optional, tag = "1")]
    pub flops_per_sec: ::core::option::Option<i32>,
    /// Memory used in bytes for the proof activity
    #[prost(int32, optional, tag = "2")]
    pub memory_used: ::core::option::Option<i32>,
    /// Memory capacity in bytes of the node
    #[prost(int32, optional, tag = "3")]
    pub memory_capacity: ::core::option::Option<i32>,
    /// Geo location of the node
    #[prost(string, optional, tag = "4")]
    pub location: ::core::option::Option<::prost::alloc::string::String>,
}
/// Paginated leaderboard.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaderboardRequest {
    /// The offset of the leaderboard to request.
    #[prost(int32, tag = "1")]
    pub offset: i32,
    /// The number of entries to request.
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
/// The response to a leaderboard request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaderboardResponse {
    #[prost(message, repeated, tag = "1")]
    pub leaderboard: ::prost::alloc::vec::Vec<LeaderboardResponseEntry>,
}
/// An entry in the leaderboard.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaderboardResponseEntry {
    /// The user's wallet public address.
    #[prost(string, tag = "1")]
    pub wallet_address: ::prost::alloc::string::String,
    /// Cycles per second proved by all of the user's nodes, averaged over the last time window.
    #[prost(double, tag = "2")]
    pub cycles_per_sec: f64,
    /// The user's rank in the leaderboard.
    #[prost(int64, tag = "3")]
    pub rank: i64,
}
/// Response to a network speed request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NetworkSpeedResponse {
    /// Cycles per second proved by all nodes in the network, averaged over the last time window.
    #[prost(double, tag = "1")]
    pub cycles_per_sec: f64,
}
/// Response to a total cycles request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TotalCyclesResponse {
    /// The total number of cycles proved by the network.
    #[prost(int64, tag = "1")]
    pub total_cycles_proved: i64,
}
/// Request the total number points for each node associated with a wallet address.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPointsRequest {
    /// The user's wallet public address.
    #[prost(string, tag = "1")]
    pub wallet_address: ::prost::alloc::string::String,
}
/// Response to a get points request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPointsResponse {
    #[prost(message, repeated, tag = "1")]
    pub points: ::prost::alloc::vec::Vec<Points>,
}
/// Total points earned by a node.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Points {
    #[prost(int64, tag = "1")]
    pub node_id: i64,
    #[prost(enumeration = "NodeType", tag = "2")]
    pub node_type: i32,
    #[prost(int64, tag = "3")]
    pub points: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeType {
    /// The node is a web prover.
    WebProver = 0,
    /// The node is a CLI prover.
    CliProver = 1,
}
impl NodeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            NodeType::WebProver => "WEB_PROVER",
            NodeType::CliProver => "CLI_PROVER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WEB_PROVER" => Some(Self::WebProver),
            "CLI_PROVER" => Some(Self::CliProver),
            _ => None,
        }
    }
}
